### ISSUE TITLE
can not build userdebug version

### ISSUE THREAD

**Issue by weimings** [Swamoy14/manifest#1]
When I lunch aosp_land-userdebug, the rom that I build still a user version and cannot root.

**Comment by Swamoy14** [comment]
Try,
. build/envsetup.sh
lunch
select aosp_land-userdebug (most probably 3)
mka bacon -j4
enjoy..

**Comment by weimings** [comment]
> Try,
> . build/envsetup.sh
> lunch
> select aosp_land-userdebug (most probably 3)
> mka bacon -j4
> enjoy..

Yeah, used this cmd before, but these properties's value "ro.secure=1" "ro.adb.secure=1" "ro.debuggable=0" in "system/etc/prop.default" that mean the rom is not a userdebug version. I cannot find "su" in "system/xbin/" and the adb debug port is not open default.

**Comment by weimings** [comment]
@Swamoy14 How do you compile and debug the rom please ?

**Comment by Swamoy14** [comment]
For security purpose even userdebug builds have these props enabled.. If you want to debug then make eng boot.img.. Better check following link..

https://www.reddit.com/r/LineageOS/comments/7p5mh4/debug_the_custom_lineageos_rom_force_usb/

**Comment by weimings** [comment]
> For security purpose even userdebug builds have these props enabled.. If you want to debug then make eng boot.img.. Better check following link..
> 
> https://www.reddit.com/r/LineageOS/comments/7p5mh4/debug_the_custom_lineageos_rom_force_usb/

OK, thank you. In my work, the code I use to compile userdebug is the default root, similar to eng, different from this...
